"""'eightt'

Revision ID: 7cb15f107ad7
Revises: None
Create Date: 2016-10-31 14:29:20.363000

"""

# revision identifiers, used by Alembic.
revision = '7cb15f107ad7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
