"""initial migration

Revision ID: 286cdea087bd
Revises: None
Create Date: 2016-10-19 12:40:40.123000

"""

# revision identifiers, used by Alembic.
revision = '286cdea087bd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
