"""initialmigration

Revision ID: 36c8ff4a061b
Revises: 286cdea087bd
Create Date: 2016-10-29 13:21:55.669000

"""

# revision identifiers, used by Alembic.
revision = '36c8ff4a061b'
down_revision = '286cdea087bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
